/* Apple Component Gallery — Cross-Platform Naming Reference */
window.CROSS_PLATFORM = {

  accordion: {
    web:     "Accordion / <details>+<summary>",
    android: "ExpansionPanel (Material)",
    flutter: "ExpansionTile / ExpansionPanelList",
    react:   "Accordion (Radix UI / Headless UI)",
  },
  alert: {
    web:     "Alert Dialog / <dialog>",
    android: "AlertDialog / MaterialAlertDialog",
    flutter: "AlertDialog / showDialog()",
    react:   "AlertDialog (Radix UI) / Modal (MUI)",
  },
  avatar: {
    web:     "Avatar",
    android: "Avatar (Material You)",
    flutter: "CircleAvatar",
    react:   "Avatar (Radix UI / MUI)",
  },
  badge: {
    web:     "Badge / Notification Dot",
    android: "BadgeDrawable (Material)",
    flutter: "Badge",
    react:   "Badge (Radix UI / MUI)",
  },
  banner: {
    web:     "Alert / Banner / Notice",
    android: "MaterialBanner (Material)",
    flutter: "MaterialBanner",
    react:   "Alert (MUI) / Banner",
  },
  bottomsheet: {
    web:     "Drawer / Bottom Sheet",
    android: "ModalBottomSheet / BottomSheetDialog",
    flutter: "showModalBottomSheet / DraggableScrollableSheet",
    react:   "Sheet (Radix UI) / Drawer (MUI)",
  },
  breadcrumb: {
    web:     "Breadcrumb",
    android: "(표준 컴포넌트 없음, 커스텀)",
    flutter: "(커스텀 구현)",
    react:   "Breadcrumb (Radix UI / MUI)",
  },
  button: {
    web:     "Button / <button>",
    android: "Button / MaterialButton",
    flutter: "ElevatedButton / TextButton / OutlinedButton",
    react:   "Button (MUI / Radix UI)",
  },
  buttongroup: {
    web:     "Button Group / Toolbar",
    android: "ToggleButtonGroup (Material)",
    flutter: "ToggleButtons",
    react:   "ToggleGroup (Radix UI) / ButtonGroup (MUI)",
  },
  card: {
    web:     "Card",
    android: "Card / MaterialCard",
    flutter: "Card",
    react:   "Card (MUI) / Box",
  },
  carousel: {
    web:     "Carousel / Slider",
    android: "ViewPager2 / HorizontalPager",
    flutter: "PageView / CarouselView",
    react:   "Carousel / Swiper",
  },
  checkbox: {
    web:     "Checkbox / <input type='checkbox'>",
    android: "Checkbox (Material)",
    flutter: "Checkbox / CheckboxListTile",
    react:   "Checkbox (Radix UI / MUI)",
  },
  combobox: {
    web:     "Select / Combobox / <select>",
    android: "Spinner / ExposedDropdownMenu",
    flutter: "DropdownButton / DropdownMenu",
    react:   "Select (Radix UI) / Combobox",
  },
  contextmenu: {
    web:     "Context Menu / Right-click Menu",
    android: "ContextMenu / PopupMenu",
    flutter: "PopupMenuButton",
    react:   "ContextMenu (Radix UI)",
  },
  datepicker: {
    web:     "<input type='date'> / Date Picker",
    android: "DatePickerDialog / MaterialDatePicker",
    flutter: "showDatePicker() / DatePicker",
    react:   "DatePicker (MUI) / Calendar (Radix UI)",
  },
  divider: {
    web:     "<hr> / Separator",
    android: "Divider (Material)",
    flutter: "Divider",
    react:   "Divider (MUI) / Separator (Radix UI)",
  },
  emptystate: {
    web:     "Empty State / No Results",
    android: "(커스텀 뷰, 표준 없음)",
    flutter: "(커스텀 위젯)",
    react:   "Empty State (커스텀)",
  },
  form: {
    web:     "<form>",
    android: "(LinearLayout / 커스텀)",
    flutter: "Form / TextFormField",
    react:   "Form (React Hook Form / Formik)",
  },
  gauge: {
    web:     "<meter> / Progress Ring",
    android: "CircularProgressIndicator",
    flutter: "CircularProgressIndicator",
    react:   "CircularProgress (MUI) / Gauge",
  },
  grid: {
    web:     "CSS Grid / Masonry",
    android: "LazyVerticalGrid / RecyclerView Grid",
    flutter: "GridView",
    react:   "Grid (MUI) / CSS Grid",
  },
  icon: {
    web:     "Icon (Font Awesome / Material Icons / Heroicons)",
    android: "Material Icons / ImageVector",
    flutter: "Icon / Icons",
    react:   "Icon (MUI) / Lucide React",
  },
  inspector: {
    web:     "Side Panel / Drawer (end)",
    android: "NavigationDrawer (end) / SideSheet",
    flutter: "Drawer (end)",
    react:   "Drawer (MUI) / Sheet (Radix UI)",
  },
  label: {
    web:     "<label> / Icon + Text",
    android: "TextView + ImageView",
    flutter: "(Row + Icon + Text)",
    react:   "Label (Radix UI)",
  },
  link: {
    web:     "<a> / Anchor / Link",
    android: "TextView (autoLink) / Intent",
    flutter: "GestureDetector / TextButton",
    react:   "Link (React Router / Next.js)",
  },
  list: {
    web:     "<ul> / <ol> / List",
    android: "LazyColumn / RecyclerView",
    flutter: "ListView / ListView.builder",
    react:   "List (MUI) / VirtualList",
  },
  loading: {
    web:     "Spinner / Loading Indicator",
    android: "CircularProgressIndicator",
    flutter: "CircularProgressIndicator",
    react:   "CircularProgress (MUI) / Spinner",
  },
  map: {
    web:     "Google Maps / Leaflet / Mapbox",
    android: "MapView (Google Maps SDK)",
    flutter: "GoogleMap / FlutterMap",
    react:   "react-map-gl / Google Maps React",
  },
  menu: {
    web:     "Dropdown Menu / <select>",
    android: "PopupMenu / DropdownMenu",
    flutter: "PopupMenuButton / DropdownMenu",
    react:   "DropdownMenu (Radix UI) / Menu (MUI)",
  },
  modal: {
    web:     "Modal / Dialog / <dialog>",
    android: "Dialog / AlertDialog",
    flutter: "showDialog() / showGeneralDialog()",
    react:   "Dialog (Radix UI) / Modal (MUI)",
  },
  navbar: {
    web:     "Navbar / Header / <nav>",
    android: "TopAppBar / ActionBar",
    flutter: "AppBar",
    react:   "AppBar (MUI) / Navbar",
  },
  notification: {
    web:     "Toast / Snackbar / Notification",
    android: "Snackbar / Toast",
    flutter: "SnackBar",
    react:   "Toast (Radix UI) / Snackbar (MUI)",
  },
  numberinput: {
    web:     "<input type='number'> / Number Input",
    android: "(커스텀, 표준 없음)",
    flutter: "(커스텀 위젯)",
    react:   "NumberInput (MUI)",
  },
  pagination: {
    web:     "Pagination / Page Indicator",
    android: "TabLayout (dots) / ViewPager dots",
    flutter: "SmoothPageIndicator (패키지)",
    react:   "Pagination (MUI) / Dots",
  },
  photopicker: {
    web:     "<input type='file' accept='image/*'>",
    android: "Photo Picker / ACTION_GET_CONTENT",
    flutter: "image_picker (패키지)",
    react:   "File Input / react-dropzone",
  },
  popover: {
    web:     "Popover / Tooltip / <popover>",
    android: "PopupWindow / Tooltip",
    flutter: "(커스텀 Overlay)",
    react:   "Popover (Radix UI / MUI)",
  },
  progressbar: {
    web:     "<progress> / Progress Bar",
    android: "LinearProgressIndicator",
    flutter: "LinearProgressIndicator",
    react:   "LinearProgress (MUI) / Progress (Radix UI)",
  },
  quote: {
    web:     "<blockquote>",
    android: "(커스텀)",
    flutter: "(커스텀 위젯)",
    react:   "<blockquote> / 커스텀",
  },
  radio: {
    web:     "<input type='radio'> / Radio Button",
    android: "RadioButton / RadioGroup",
    flutter: "Radio / RadioListTile",
    react:   "RadioGroup (Radix UI / MUI)",
  },
  rating: {
    web:     "Star Rating / Rating",
    android: "RatingBar",
    flutter: "RatingBar (flutter_rating_bar)",
    react:   "Rating (MUI)",
  },
  searchbar: {
    web:     "<input type='search'> / Search Box",
    android: "SearchView / SearchBar (Material)",
    flutter: "SearchBar / SearchAnchor",
    react:   "Autocomplete (MUI) / Combobox",
  },
  segmented: {
    web:     "Segmented Button / Radio Group (styled)",
    android: "SegmentedButton (Material You)",
    flutter: "SegmentedButton",
    react:   "ToggleButtonGroup (MUI) / SegmentedControl",
  },
  sidebar: {
    web:     "Sidebar / Navigation Drawer",
    android: "NavigationDrawer / NavigationRail",
    flutter: "NavigationDrawer / NavigationRail",
    react:   "Drawer (MUI) / Sidebar",
  },
  skeleton: {
    web:     "Skeleton / Shimmer",
    android: "Shimmer (Facebook) / Placeholder",
    flutter: "Shimmer (shimmer 패키지)",
    react:   "Skeleton (MUI / Radix UI)",
  },
  slider: {
    web:     "<input type='range'> / Slider",
    android: "Slider (Material)",
    flutter: "Slider / RangeSlider",
    react:   "Slider (MUI / Radix UI)",
  },
  spacer: {
    web:     "CSS gap / margin / Spacer",
    android: "Spacer (Compose) / View weight",
    flutter: "Spacer / SizedBox",
    react:   "Box (flex gap) / Spacer",
  },
  switch: {
    web:     "Toggle / Switch",
    android: "Switch / SwitchMaterial",
    flutter: "Switch / SwitchListTile",
    react:   "Switch (MUI / Radix UI)",
  },
  tabbar: {
    web:     "Bottom Navigation / Tab Bar",
    android: "BottomNavigationView / NavigationBar",
    flutter: "BottomNavigationBar / NavigationBar",
    react:   "BottomNavigation (MUI) / Tabs",
  },
  table: {
    web:     "<table> / DataGrid",
    android: "RecyclerView (표 형태)",
    flutter: "DataTable",
    react:   "DataGrid (MUI) / TanStack Table",
  },
  tabs: {
    web:     "Tabs",
    android: "TabLayout / TabRow",
    flutter: "TabBar + TabBarView",
    react:   "Tabs (Radix UI / MUI)",
  },
  textfield: {
    web:     "<input> / <textarea> / Text Input",
    android: "TextField (Material) / EditText",
    flutter: "TextField / TextFormField",
    react:   "TextField (MUI) / Input (Radix UI)",
  },
  timeline: {
    web:     "Timeline",
    android: "Timeline (커스텀)",
    flutter: "Timeline (커스텀)",
    react:   "Timeline (MUI)",
  },
  tipview: {
    web:     "Tooltip / Coach Mark / Popover",
    android: "Tooltip (Material)",
    flutter: "Tooltip",
    react:   "Tooltip (Radix UI / MUI)",
  },
  toolbar: {
    web:     "Toolbar / Action Bar",
    android: "Toolbar / TopAppBar",
    flutter: "AppBar (actions)",
    react:   "Toolbar (MUI)",
  },
  treeview: {
    web:     "Tree View / Tree",
    android: "ExpandableListView (RecyclerView)",
    flutter: "(커스텀 위젯)",
    react:   "TreeView (MUI) / Tree (Radix UI)",
  },
  video: {
    web:     "<video> / Media Player",
    android: "VideoView / ExoPlayer",
    flutter: "VideoPlayer (video_player 패키지)",
    react:   "ReactPlayer / Video.js",
  },
  widget: {
    web:     "(해당 없음 - 홈 화면 위젯)",
    android: "AppWidget / Glance",
    flutter: "(홈 화면 위젯 미지원)",
    react:   "(해당 없음)",
  },
  colorpicker: {
    web:     "<input type='color'> / Color Picker",
    android: "(커스텀, 표준 없음)",
    flutter: "ColorPicker (flutter_colorpicker)",
    react:   "ColorPicker (react-colorful / MUI)",
  },
  sharesheet: {
    web:     "Web Share API / navigator.share()",
    android: "ShareCompat / Intent.ACTION_SEND",
    flutter: "Share (share_plus 패키지)",
    react:   "Web Share API / react-share",
  },
  scrollview: {
    web:     "overflow: scroll / Scroll Area",
    android: "ScrollView / LazyColumn",
    flutter: "SingleChildScrollView / ListView",
    react:   "ScrollArea (Radix UI) / 커스텀",
  },
  statusbar: {
    web:     "(브라우저 UI, 제어 불가)",
    android: "StatusBar / WindowInsetsController",
    flutter: "SystemChrome.setSystemUIOverlayStyle()",
    react:   "StatusBar (React Native)",
  },

};
