/* Apple Component Gallery — Visual Previews */
window.PREVIEWS = {

accordion: `<div class="pv-wrap"><div class="pv-card"><div class="pv-row"><span class="pv-label">⚙️ Settings</span><span style="color:#C7C7CC;font-size:16px">▾</span></div><div style="background:#F9F9F9;padding:4px 16px 4px 28px;border-bottom:0.5px solid #E5E5EA"><div class="pv-row" style="border:none;padding:8px 0"><span class="pv-label" style="font-size:14px">Wi-Fi</span><div class="pv-switch pv-switch-on"><div class="pv-thumb"></div></div></div><div class="pv-row" style="border:none;padding:8px 0"><span class="pv-label" style="font-size:14px">Bluetooth</span><div class="pv-switch pv-switch-off"><div class="pv-thumb"></div></div></div></div><div class="pv-row"><span class="pv-label">🔒 Privacy</span><span style="color:#C7C7CC;font-size:16px">▸</span></div></div></div>`,

alert: `<div style="background:rgba(0,0,0,0.35);padding:20px;border-radius:12px;width:100%;max-width:300px;display:flex;align-items:center;justify-content:center"><div style="background:rgba(242,242,247,0.97);border-radius:14px;width:270px;text-align:center;overflow:hidden"><div style="padding:20px 16px 12px"><div style="font-size:17px;font-weight:600;margin-bottom:4px">Delete Item?</div><div style="font-size:13px;color:#666">This cannot be undone.</div></div><div style="border-top:0.5px solid #C7C7CC;display:flex"><div style="flex:1;padding:12px;color:#007AFF;font-size:17px;border-right:0.5px solid #C7C7CC">Cancel</div><div style="flex:1;padding:12px;color:#FF3B30;font-size:17px;font-weight:600">Delete</div></div></div></div>`,

avatar: `<div style="display:flex;align-items:center;gap:16px;justify-content:center"><div style="width:44px;height:44px;border-radius:22px;background:linear-gradient(135deg,#007AFF,#5856D6);display:flex;align-items:center;justify-content:center;color:white;font-size:16px;font-weight:700">JD</div><div style="width:60px;height:60px;border-radius:30px;background:linear-gradient(135deg,#FF9500,#FF2D55);display:flex;align-items:center;justify-content:center;color:white;font-size:22px;font-weight:700">AB</div><div style="width:80px;height:80px;border-radius:40px;background:linear-gradient(135deg,#34C759,#30B0C7);display:flex;align-items:center;justify-content:center;font-size:36px">😊</div></div>`,

badge: `<div class="pv-wrap"><div class="pv-card"><div class="pv-row"><span class="pv-label">📥 Inbox</span><span class="pv-badge">5</span></div><div class="pv-row"><span class="pv-label">📝 Drafts</span><span class="pv-badge" style="background:#8E8E93">New</span></div><div class="pv-row"><span class="pv-label">✅ Sent</span><span class="pv-value">—</span></div></div></div>`,

banner: `<div style="width:100%;max-width:300px;background:rgba(0,122,255,0.1);border-radius:10px;padding:12px 16px;display:flex;align-items:center;gap:12px"><span style="font-size:20px">ℹ️</span><div style="flex:1"><div style="font-size:14px;font-weight:600;color:#007AFF">Update Available</div><div style="font-size:12px;color:#007AFF;opacity:0.8">Version 2.1 is ready</div></div><button class="pv-btn pv-btn-primary" style="padding:5px 12px;font-size:12px">Update</button></div>`,

bottomsheet: `<div style="width:100%;max-width:300px"><div style="background:white;border-radius:16px 16px 0 0;padding:8px 20px 16px;box-shadow:0 -4px 20px rgba(0,0,0,0.15)"><div style="width:36px;height:4px;background:#E5E5EA;border-radius:2px;margin:0 auto 16px"></div><div style="font-size:17px;font-weight:600;margin-bottom:12px;text-align:center">Options</div><div class="pv-card"><div class="pv-row"><span class="pv-label">Share</span></div><div class="pv-row"><span class="pv-label">Copy Link</span></div><div class="pv-row"><span class="pv-label" style="color:#FF3B30">Delete</span></div></div></div></div>`,

breadcrumb: `<div style="display:flex;align-items:center;gap:4px;font-size:14px;flex-wrap:wrap;justify-content:center"><span style="color:#8E8E93">Home</span><span style="color:#C7C7CC;font-size:16px">›</span><span style="color:#8E8E93">Library</span><span style="color:#C7C7CC;font-size:16px">›</span><span style="color:#8E8E93">Music</span><span style="color:#C7C7CC;font-size:16px">›</span><span style="color:#007AFF;font-weight:500">Albums</span></div>`,

button: `<div style="display:flex;flex-direction:column;gap:10px;align-items:center;width:100%;max-width:240px"><button class="pv-btn pv-btn-primary" style="width:100%">💾 Save</button><button class="pv-btn pv-btn-secondary" style="width:100%">Cancel</button><button class="pv-btn pv-btn-destructive" style="width:100%">Delete</button></div>`,

buttongroup: `<div style="display:flex;flex-direction:column;gap:12px;align-items:center"><div style="background:white;border:0.5px solid #E5E5EA;border-radius:10px;display:inline-flex;overflow:hidden"><button style="padding:10px 18px;border:none;background:none;font-size:16px;border-right:0.5px solid #E5E5EA;cursor:default;font-weight:700">B</button><button style="padding:10px 18px;border:none;background:none;font-size:16px;border-right:0.5px solid #E5E5EA;cursor:default;font-style:italic">I</button><button style="padding:10px 18px;border:none;background:none;font-size:16px;cursor:default;text-decoration:underline">U</button></div><div style="background:white;border:0.5px solid #E5E5EA;border-radius:10px;display:inline-flex;overflow:hidden"><button style="padding:8px 14px;border:none;background:#007AFF;color:white;cursor:default;font-size:14px">◀</button><button style="padding:8px 14px;border:none;background:none;border-left:0.5px solid #E5E5EA;cursor:default;font-size:14px">▶</button></div></div>`,

card: `<div style="background:white;border-radius:14px;overflow:hidden;width:220px;box-shadow:0 2px 10px rgba(0,0,0,0.1)"><div style="height:100px;background:linear-gradient(135deg,#007AFF,#5856D6);display:flex;align-items:center;justify-content:center;font-size:44px">🏔️</div><div style="padding:12px"><div style="font-size:15px;font-weight:600;margin-bottom:4px">Mountain View</div><div style="font-size:13px;color:#8E8E93;line-height:1.4">Explore breathtaking landscapes and scenic trails.</div></div></div>`,

carousel: `<div style="width:100%;max-width:280px"><div style="background:linear-gradient(135deg,#007AFF,#5856D6);border-radius:12px;height:120px;display:flex;align-items:center;justify-content:center;font-size:44px;margin-bottom:10px">🌅</div><div style="display:flex;justify-content:center;gap:6px"><div style="width:20px;height:8px;border-radius:4px;background:#007AFF"></div><div style="width:8px;height:8px;border-radius:4px;background:#E5E5EA"></div><div style="width:8px;height:8px;border-radius:4px;background:#E5E5EA"></div><div style="width:8px;height:8px;border-radius:4px;background:#E5E5EA"></div></div></div>`,

checkbox: `<div class="pv-wrap"><div class="pv-card"><div class="pv-row"><span class="pv-label">Notifications</span><span style="width:24px;height:24px;border-radius:6px;background:#007AFF;display:inline-flex;align-items:center;justify-content:center;color:white;font-size:14px;font-weight:700">✓</span></div><div class="pv-row"><span class="pv-label">Analytics</span><span style="width:24px;height:24px;border-radius:6px;background:white;border:2px solid #E5E5EA;display:inline-block"></span></div><div class="pv-row"><span class="pv-label">Location</span><span style="width:24px;height:24px;border-radius:6px;background:#007AFF;display:inline-flex;align-items:center;justify-content:center;color:white;font-size:14px;font-weight:700">✓</span></div></div></div>`,

combobox: `<div style="width:100%;max-width:260px"><div style="background:white;border:1px solid #E5E5EA;border-radius:10px;padding:10px 14px;display:flex;justify-content:space-between;align-items:center;margin-bottom:4px"><span style="font-size:15px">Sort by: Name</span><span style="color:#8E8E93">⌄</span></div><div style="background:white;border:1px solid #E5E5EA;border-radius:10px;overflow:hidden"><div class="pv-row" style="padding:10px 14px"><span style="color:#007AFF;font-weight:500">Name</span><span>✓</span></div><div class="pv-row" style="padding:10px 14px"><span>Date</span></div><div class="pv-row" style="padding:10px 14px"><span>Size</span></div></div></div>`,

contextmenu: `<div style="display:flex;gap:16px;align-items:flex-start;justify-content:center"><div style="background:white;border-radius:10px;padding:12px;font-size:28px;box-shadow:0 2px 8px rgba(0,0,0,0.1);text-align:center">🖼️<div style="font-size:11px;color:#8E8E93;margin-top:4px">Photo</div></div><div style="background:rgba(255,255,255,0.97);border-radius:12px;min-width:180px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.15)"><div class="pv-row" style="padding:10px 16px;font-size:14px"><span>Copy</span><span style="color:#8E8E93;font-size:12px">⌘C</span></div><div class="pv-row" style="padding:10px 16px;font-size:14px"><span>Share</span><span style="color:#8E8E93;font-size:12px">↑</span></div><div style="height:0.5px;background:#E5E5EA"></div><div style="padding:10px 16px;font-size:14px;color:#FF3B30">Delete</div></div></div>`,

datepicker: `<div style="background:white;border-radius:12px;padding:14px;width:220px"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><span style="font-size:18px;color:#C7C7CC">‹</span><span style="font-size:15px;font-weight:600">March 2026</span><span style="font-size:18px;color:#007AFF">›</span></div><div style="display:grid;grid-template-columns:repeat(7,1fr);gap:2px;text-align:center;font-size:11px;color:#8E8E93;margin-bottom:4px"><span>S</span><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span></div><div style="display:grid;grid-template-columns:repeat(7,1fr);gap:2px;text-align:center;font-size:13px"><span style="color:#C7C7CC">23</span><span style="color:#C7C7CC">24</span><span style="color:#C7C7CC">25</span><span style="color:#C7C7CC">26</span><span style="color:#C7C7CC">27</span><span style="color:#C7C7CC">28</span><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span style="background:#007AFF;color:white;border-radius:14px;padding:2px 0">6</span><span>7</span><span>8</span><span>9</span><span>10</span><span>11</span><span>12</span><span>13</span><span>14</span><span>15</span></div></div>`,

divider: `<div style="width:100%;max-width:280px"><div style="padding:10px 0;font-size:15px;color:#000">Section 1 content</div><div style="height:0.5px;background:#E5E5EA"></div><div style="padding:10px 0;font-size:15px;color:#000">Section 2 content</div><div style="height:0.5px;background:#E5E5EA"></div><div style="padding:10px 0;font-size:15px;color:#000">Section 3 content</div></div>`,

emptystate: `<div style="text-align:center;padding:10px"><div style="font-size:48px;margin-bottom:12px">🔍</div><div style="font-size:17px;font-weight:600;margin-bottom:6px">No Results</div><div style="font-size:14px;color:#8E8E93;margin-bottom:16px">Try a different search term.</div><button class="pv-btn pv-btn-secondary" style="font-size:14px">Clear Search</button></div>`,

form: `<div class="pv-wrap"><div class="pv-section">Profile</div><div class="pv-card"><div class="pv-row"><span class="pv-label">Name</span><span class="pv-value">John Doe</span></div><div class="pv-row"><span class="pv-label">Birthday</span><span class="pv-value">Jun 15</span></div></div><div class="pv-section" style="margin-top:10px">Preferences</div><div class="pv-card"><div class="pv-row"><span class="pv-label">Notifications</span><div class="pv-switch pv-switch-on"><div class="pv-thumb"></div></div></div><div class="pv-row"><span class="pv-label">Theme</span><span class="pv-value">System <span class="pv-chev"></span></span></div></div></div>`,

gauge: `<div style="display:flex;gap:24px;align-items:center;justify-content:center;flex-wrap:wrap"><div style="text-align:center"><div style="position:relative;width:80px;height:80px;margin:0 auto 6px"><svg viewBox="0 0 80 80" style="transform:rotate(-90deg);width:80px;height:80px"><circle cx="40" cy="40" r="32" fill="none" stroke="#E5E5EA" stroke-width="8"/><circle cx="40" cy="40" r="32" fill="none" stroke="#007AFF" stroke-width="8" stroke-dasharray="134 67" stroke-linecap="round"/></svg><div style="position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center"><span style="font-size:17px;font-weight:700">67%</span></div></div><div style="font-size:12px;color:#8E8E93">Battery</div></div><div style="text-align:center"><div style="position:relative;width:64px;height:64px;margin:0 auto 6px"><svg viewBox="0 0 80 80" style="transform:rotate(-90deg);width:64px;height:64px"><circle cx="40" cy="40" r="32" fill="none" stroke="#E5E5EA" stroke-width="8"/><circle cx="40" cy="40" r="32" fill="none" stroke="#34C759" stroke-width="8" stroke-dasharray="80 120" stroke-linecap="round"/></svg><div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center"><span style="font-size:14px;font-weight:700">40%</span></div></div><div style="font-size:12px;color:#8E8E93">Storage</div></div></div>`,

grid: `<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;width:100%;max-width:240px"><div style="aspect-ratio:1;background:linear-gradient(135deg,#007AFF,#5856D6);border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px">🏔️</div><div style="aspect-ratio:1;background:linear-gradient(135deg,#FF9500,#FF2D55);border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px">🌅</div><div style="aspect-ratio:1;background:linear-gradient(135deg,#34C759,#30D158);border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px">🌿</div><div style="aspect-ratio:1;background:linear-gradient(135deg,#FF2D55,#FF9500);border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px">🌺</div><div style="aspect-ratio:1;background:linear-gradient(135deg,#5856D6,#007AFF);border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px">🌊</div><div style="aspect-ratio:1;background:linear-gradient(135deg,#FF9500,#34C759);border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px">🌲</div></div>`,

icon: `<div style="display:flex;gap:20px;flex-wrap:wrap;justify-content:center"><div style="text-align:center"><div style="font-size:38px">❤️</div><div style="font-size:10px;color:#8E8E93;margin-top:4px">heart.fill</div></div><div style="text-align:center"><div style="font-size:38px">⭐</div><div style="font-size:10px;color:#8E8E93;margin-top:4px">star.fill</div></div><div style="text-align:center"><div style="font-size:38px">🔔</div><div style="font-size:10px;color:#8E8E93;margin-top:4px">bell.fill</div></div><div style="text-align:center"><div style="font-size:38px">📍</div><div style="font-size:10px;color:#8E8E93;margin-top:4px">location.fill</div></div></div>`,

inspector: `<div style="display:flex;width:100%;max-width:320px;border:1px solid #E5E5EA;border-radius:10px;overflow:hidden;height:150px"><div style="flex:1;padding:12px;border-right:0.5px solid #E5E5EA;background:white"><div style="font-size:14px;font-weight:600;margin-bottom:8px">📄 Document</div><div style="font-size:12px;color:#8E8E93">Main content area</div></div><div style="width:140px;padding:12px;background:#F9F9F9"><div style="font-size:11px;color:#8E8E93;text-transform:uppercase;font-weight:600;margin-bottom:8px;letter-spacing:0.5px">Inspector</div><div style="font-size:12px;margin-bottom:6px;display:flex;justify-content:space-between"><span style="color:#8E8E93">Name</span><span>doc.txt</span></div><div style="font-size:12px;margin-bottom:6px;display:flex;justify-content:space-between"><span style="color:#8E8E93">Size</span><span>24 KB</span></div><div style="font-size:12px;display:flex;justify-content:space-between"><span style="color:#8E8E93">Date</span><span>Today</span></div></div></div>`,

label: `<div style="display:flex;flex-direction:column;gap:10px;align-items:flex-start"><div style="display:flex;align-items:center;gap:8px;font-size:16px;font-weight:500"><span style="font-size:20px">❤️</span>Favorites</div><div style="display:flex;align-items:center;gap:8px;font-size:16px;font-weight:500"><span style="font-size:20px">⭐</span>Starred</div><div style="display:flex;justify-content:space-between;align-items:center;font-size:15px;background:white;border-radius:8px;padding:8px 14px;width:200px"><span style="color:#8E8E93">Version</span><span>2.1.0</span></div></div>`,

link: `<div style="display:flex;flex-direction:column;gap:12px;width:100%;max-width:260px"><div style="font-size:15px;color:#007AFF;text-decoration:underline;text-underline-offset:2px">Visit Apple.com ↗</div><div class="pv-card"><div class="pv-row"><span style="color:#007AFF;font-size:15px">Settings</span><span class="pv-chev"></span></div><div class="pv-row"><span style="color:#007AFF;font-size:15px">Profile</span><span class="pv-chev"></span></div></div></div>`,

list: `<div class="pv-wrap"><div class="pv-section">Favorites</div><div class="pv-card"><div class="pv-row"><span style="font-size:18px;margin-right:8px">🎵</span><span class="pv-label">Taylor Swift</span><span class="pv-chev"></span></div><div class="pv-row"><span style="font-size:18px;margin-right:8px">🎸</span><span class="pv-label">The Beatles</span><span class="pv-chev"></span></div><div class="pv-row"><span style="font-size:18px;margin-right:8px">🎹</span><span class="pv-label">Coldplay</span><span class="pv-chev"></span></div></div></div>`,

loading: `<div style="display:flex;gap:28px;align-items:center;justify-content:center"><div style="text-align:center"><div style="width:44px;height:44px;border-radius:22px;border:3px solid #E5E5EA;border-top-color:#007AFF;animation:pvSpin 0.8s linear infinite;margin:0 auto 8px"></div><div style="font-size:12px;color:#8E8E93">Large</div></div><div style="text-align:center"><div style="width:28px;height:28px;border-radius:14px;border:2.5px solid #E5E5EA;border-top-color:#007AFF;animation:pvSpin 0.8s linear infinite;margin:0 auto 8px"></div><div style="font-size:12px;color:#8E8E93">Regular</div></div><div style="text-align:center"><div style="width:20px;height:20px;border-radius:10px;border:2px solid #E5E5EA;border-top-color:#007AFF;animation:pvSpin 0.8s linear infinite;margin:0 auto 8px"></div><div style="font-size:12px;color:#8E8E93">Small</div></div></div>`,

map: `<div style="width:100%;max-width:300px;height:140px;background:linear-gradient(180deg,#93C5E8 0%,#93C5E8 35%,#C8DEB8 35%,#B8D4A0 65%,#A8C890 65%);border-radius:12px;position:relative;overflow:hidden"><div style="position:absolute;inset:0;opacity:0.15;background:repeating-linear-gradient(0deg,transparent,transparent 20px,rgba(0,0,0,0.05) 20px,rgba(0,0,0,0.05) 21px),repeating-linear-gradient(90deg,transparent,transparent 20px,rgba(0,0,0,0.05) 20px,rgba(0,0,0,0.05) 21px)"></div><div style="position:absolute;top:45%;left:50%;transform:translate(-50%,-100%);text-align:center"><div style="font-size:28px">📍</div><div style="background:white;border-radius:8px;padding:3px 10px;font-size:11px;font-weight:600;box-shadow:0 2px 6px rgba(0,0,0,0.2);white-space:nowrap">Apple Park</div></div><div style="position:absolute;bottom:8px;right:8px;background:white;border-radius:8px;padding:4px 8px;font-size:11px;color:#007AFF;box-shadow:0 1px 4px rgba(0,0,0,0.1)">📍 My Location</div></div>`,

menu: `<div style="display:flex;flex-direction:column;align-items:flex-start;gap:0;position:relative;padding-top:4px"><button class="pv-btn pv-btn-secondary" style="padding:8px 14px;font-size:14px;margin-bottom:8px">Options ⌄</button><div style="background:rgba(255,255,255,0.97);border-radius:12px;min-width:190px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.15)"><div class="pv-row" style="padding:10px 16px;font-size:14px"><span>🗂️ Duplicate</span></div><div class="pv-row" style="padding:10px 16px;font-size:14px"><span>✏️ Rename</span></div><div style="height:0.5px;background:#E5E5EA"></div><div style="padding:10px 16px;font-size:14px;color:#FF3B30">🗑️ Delete</div></div></div>`,

modal: `<div style="width:100%;max-width:300px"><div style="background:white;border-radius:16px 16px 0 0;padding:0 0 16px;box-shadow:0 -8px 40px rgba(0,0,0,0.2)"><div style="padding:14px 16px;border-bottom:0.5px solid #E5E5EA;display:flex;justify-content:space-between;align-items:center"><button style="font-size:15px;color:#007AFF;border:none;background:none;cursor:default">Cancel</button><span style="font-size:15px;font-weight:600">Edit Profile</span><button style="font-size:15px;color:#007AFF;font-weight:600;border:none;background:none;cursor:default">Save</button></div><div style="padding:16px 20px"><div style="font-size:13px;color:#8E8E93;margin-bottom:6px">Name</div><div style="border:1.5px solid #007AFF;border-radius:8px;padding:10px 12px;font-size:15px">John Doe</div></div></div></div>`,

navbar: `<div style="width:100%;max-width:300px;background:rgba(242,242,247,0.97);border-radius:12px;overflow:hidden;border:0.5px solid #E5E5EA"><div style="padding:40px 16px 10px;display:flex;justify-content:space-between;align-items:flex-end"><div style="font-size:28px;font-weight:700">Home</div><button style="font-size:26px;color:#007AFF;border:none;background:none;cursor:default;line-height:1">+</button></div><div style="height:0.5px;background:#E5E5EA"></div><div style="padding:10px 16px;font-size:13px;color:#8E8E93">Content below navigation bar</div></div>`,

notification: `<div style="display:flex;flex-direction:column;gap:8px;width:100%;max-width:280px"><div style="background:rgba(30,30,30,0.9);color:white;border-radius:14px;padding:12px 16px;display:flex;align-items:center;gap:10px"><span style="font-size:18px">✅</span><span style="font-size:14px;font-weight:500">Saved successfully!</span></div><div style="background:rgba(30,30,30,0.9);color:white;border-radius:14px;padding:12px 16px;display:flex;align-items:center;gap:10px;opacity:0.5"><span style="font-size:18px">🔔</span><span style="font-size:14px;font-weight:500">New message from Alex</span></div></div>`,

numberinput: `<div style="display:flex;flex-direction:column;gap:14px;width:100%;max-width:260px"><div style="display:flex;align-items:center;justify-content:space-between"><span style="font-size:15px">Quantity: 3</span><div style="display:flex;border:1px solid #E5E5EA;border-radius:8px;overflow:hidden;background:white"><button style="width:38px;height:34px;font-size:22px;border:none;border-right:0.5px solid #E5E5EA;color:#007AFF;cursor:default;background:none">−</button><button style="width:38px;height:34px;font-size:22px;border:none;color:#007AFF;cursor:default;background:none">+</button></div></div><div style="display:flex;align-items:center;justify-content:space-between"><span style="font-size:15px">Font Size: 16</span><div style="display:flex;border:1px solid #E5E5EA;border-radius:8px;overflow:hidden;background:white"><button style="width:38px;height:34px;font-size:22px;border:none;border-right:0.5px solid #E5E5EA;color:#007AFF;cursor:default;background:none">−</button><button style="width:38px;height:34px;font-size:22px;border:none;color:#007AFF;cursor:default;background:none">+</button></div></div></div>`,

pagination: `<div style="display:flex;flex-direction:column;align-items:center;gap:14px;width:100%;max-width:280px"><div style="background:linear-gradient(135deg,#5856D6,#007AFF);border-radius:12px;height:100px;width:100%;display:flex;align-items:center;justify-content:center;color:white;font-size:17px;font-weight:600">Page 2 of 4</div><div style="display:flex;gap:6px;align-items:center"><div style="width:8px;height:8px;border-radius:4px;background:#E5E5EA"></div><div style="width:20px;height:8px;border-radius:4px;background:#007AFF"></div><div style="width:8px;height:8px;border-radius:4px;background:#E5E5EA"></div><div style="width:8px;height:8px;border-radius:4px;background:#E5E5EA"></div></div></div>`,

photopicker: `<div style="width:100%;max-width:280px"><button class="pv-btn pv-btn-secondary" style="width:100%;margin-bottom:10px;font-size:14px">🖼️ Select Photos</button><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:4px"><div style="aspect-ratio:1;background:linear-gradient(135deg,#FF9500,#FF3B30);border-radius:6px"></div><div style="aspect-ratio:1;background:linear-gradient(135deg,#007AFF,#5856D6);border-radius:6px;position:relative"><div style="position:absolute;top:4px;right:4px;width:20px;height:20px;background:#007AFF;border-radius:10px;border:2px solid white;display:flex;align-items:center;justify-content:center;color:white;font-size:11px;font-weight:700">✓</div></div><div style="aspect-ratio:1;background:linear-gradient(135deg,#34C759,#30D158);border-radius:6px"></div><div style="aspect-ratio:1;background:linear-gradient(135deg,#FF2D55,#FF9500);border-radius:6px"></div><div style="aspect-ratio:1;background:linear-gradient(135deg,#5AC8FA,#007AFF);border-radius:6px"></div><div style="aspect-ratio:1;background:#E5E5EA;border-radius:6px;display:flex;align-items:center;justify-content:center;font-size:20px;color:#8E8E93">+</div></div></div>`,

popover: `<div style="display:flex;flex-direction:column;align-items:center;gap:8px"><button class="pv-btn pv-btn-secondary" style="font-size:14px">ℹ️ Info</button><div style="background:rgba(255,255,255,0.97);border-radius:12px;padding:14px 16px;width:200px;box-shadow:0 4px 20px rgba(0,0,0,0.15);position:relative"><div style="position:absolute;top:-8px;left:50%;transform:translateX(-50%);border-left:8px solid transparent;border-right:8px solid transparent;border-bottom:8px solid rgba(255,255,255,0.97)"></div><div style="font-size:14px;font-weight:600;margin-bottom:6px">Details</div><div style="font-size:13px;color:#8E8E93;line-height:1.4">Tap the heart icon to add items to your favorites list.</div></div></div>`,

progressbar: `<div style="width:100%;max-width:280px"><div style="display:flex;justify-content:space-between;font-size:13px;margin-bottom:6px"><span>Downloading...</span><span style="color:#8E8E93">67%</span></div><div class="pv-progress" style="margin-bottom:16px"><div class="pv-progress-fill" style="width:67%"></div></div><div style="display:flex;justify-content:space-between;font-size:13px;margin-bottom:6px"><span>Installing...</span><span style="color:#8E8E93">32%</span></div><div class="pv-progress"><div class="pv-progress-fill" style="width:32%;background:#34C759"></div></div></div>`,

quote: `<div style="width:100%;max-width:280px"><div style="display:flex;gap:12px;align-items:flex-start"><div style="width:4px;background:#007AFF;border-radius:2px;align-self:stretch;flex-shrink:0"></div><div><div style="font-size:15px;font-style:italic;line-height:1.55;margin-bottom:6px">"The best way to predict the future is to design it."</div><div style="font-size:13px;color:#8E8E93">— Buckminster Fuller</div></div></div></div>`,

radio: `<div class="pv-wrap"><div class="pv-card"><div class="pv-row"><span class="pv-label">Small</span><div style="width:22px;height:22px;border-radius:11px;border:2px solid #E5E5EA;flex-shrink:0"></div></div><div class="pv-row"><span class="pv-label">Medium</span><div style="width:22px;height:22px;border-radius:11px;border:2px solid #007AFF;display:flex;align-items:center;justify-content:center;flex-shrink:0"><div style="width:12px;height:12px;border-radius:6px;background:#007AFF"></div></div></div><div class="pv-row"><span class="pv-label">Large</span><div style="width:22px;height:22px;border-radius:11px;border:2px solid #E5E5EA;flex-shrink:0"></div></div></div></div>`,

rating: `<div style="display:flex;flex-direction:column;gap:10px;align-items:center"><div style="display:flex;gap:4px"><span style="font-size:34px;color:#FFD60A">★</span><span style="font-size:34px;color:#FFD60A">★</span><span style="font-size:34px;color:#FFD60A">★</span><span style="font-size:34px;color:#FFD60A">★</span><span style="font-size:34px;color:#E5E5EA">★</span></div><div style="font-size:14px;color:#8E8E93">4 out of 5 stars · 1,204 ratings</div></div>`,

searchbar: `<div style="width:100%;max-width:280px"><div style="background:rgba(120,120,128,0.12);border-radius:10px;padding:8px 12px;display:flex;align-items:center;gap:8px;margin-bottom:12px"><span style="font-size:14px;color:#8E8E93">🔍</span><span style="font-size:15px;color:#8E8E93;flex:1">Search...</span></div><div class="pv-card"><div class="pv-row"><span class="pv-label">Button</span><span class="pv-chev"></span></div><div class="pv-row"><span class="pv-label">Badge</span><span class="pv-chev"></span></div><div class="pv-row"><span class="pv-label">Card</span><span class="pv-chev"></span></div></div></div>`,

segmented: `<div style="width:100%;max-width:260px;display:flex;flex-direction:column;gap:14px"><div class="pv-seg"><div class="pv-seg-item pv-active">List</div><div class="pv-seg-item">Grid</div><div class="pv-seg-item">Map</div></div><div class="pv-seg"><div class="pv-seg-item">Day</div><div class="pv-seg-item pv-active">Week</div><div class="pv-seg-item">Month</div></div></div>`,

sidebar: `<div style="display:flex;width:100%;max-width:320px;height:160px;border:1px solid #E5E5EA;border-radius:12px;overflow:hidden"><div style="width:130px;background:#F9F9F9;border-right:0.5px solid #E5E5EA;padding:10px 0"><div style="padding:8px 12px;display:flex;align-items:center;gap:8px;background:rgba(0,122,255,0.1);border-radius:8px;margin:0 8px 4px"><span>📥</span><span style="font-size:13px;color:#007AFF;font-weight:500">All</span></div><div style="padding:8px 12px;display:flex;align-items:center;gap:8px;margin:0 8px 4px"><span>❤️</span><span style="font-size:13px">Favorites</span></div><div style="padding:8px 12px;display:flex;align-items:center;gap:8px;margin:0 8px"><span>🕒</span><span style="font-size:13px">Recent</span></div></div><div style="flex:1;padding:14px;background:white"><div style="font-size:15px;font-weight:600;margin-bottom:6px">All Items</div><div style="font-size:13px;color:#8E8E93">Select an item to view details in this area.</div></div></div>`,

skeleton: `<div style="width:100%;max-width:280px;background:white;border-radius:12px;padding:16px"><div style="display:flex;align-items:center;gap:12px;margin-bottom:14px"><div class="pv-skeleton" style="width:44px;height:44px;border-radius:22px;flex-shrink:0"></div><div style="flex:1"><div class="pv-skeleton" style="height:14px;width:70%;margin-bottom:7px"></div><div class="pv-skeleton" style="height:12px;width:45%"></div></div></div><div class="pv-skeleton" style="height:12px;width:100%;margin-bottom:7px"></div><div class="pv-skeleton" style="height:12px;width:85%;margin-bottom:7px"></div><div class="pv-skeleton" style="height:12px;width:60%"></div></div>`,

slider: `<div style="width:100%;max-width:280px"><div style="display:flex;align-items:center;gap:10px;margin-bottom:18px"><span style="font-size:18px">🔅</span><div style="flex:1;position:relative;height:4px;background:#E5E5EA;border-radius:2px"><div style="position:absolute;left:0;top:0;width:65%;height:100%;background:#007AFF;border-radius:2px"></div><div style="position:absolute;left:65%;top:50%;transform:translate(-50%,-50%);width:24px;height:24px;background:white;border-radius:12px;box-shadow:0 2px 6px rgba(0,0,0,0.25)"></div></div><span style="font-size:18px">🔆</span></div><div style="display:flex;align-items:center;gap:10px"><span style="font-size:18px">🔇</span><div style="flex:1;position:relative;height:4px;background:#E5E5EA;border-radius:2px"><div style="position:absolute;left:0;top:0;width:30%;height:100%;background:#007AFF;border-radius:2px"></div><div style="position:absolute;left:30%;top:50%;transform:translate(-50%,-50%);width:24px;height:24px;background:white;border-radius:12px;box-shadow:0 2px 6px rgba(0,0,0,0.25)"></div></div><span style="font-size:18px">🔊</span></div></div>`,

spacer: `<div style="width:100%;max-width:280px"><div style="background:white;border-radius:10px;padding:12px 16px;display:flex;align-items:center;margin-bottom:8px"><span style="font-size:15px;font-weight:500">Title</span><div style="flex:1"></div><button style="font-size:14px;color:#007AFF;border:none;background:none;cursor:default">Action</button></div><div style="background:rgba(0,122,255,0.06);border:1px dashed rgba(0,122,255,0.3);border-radius:8px;padding:8px 16px;text-align:center;font-size:12px;color:#007AFF;margin-bottom:8px">Spacer (flexible)</div><div style="background:white;border-radius:10px;padding:12px 16px;text-align:center"><span style="font-size:13px;color:#8E8E93">Pushed to bottom</span></div></div>`,

switch: `<div class="pv-wrap"><div class="pv-card"><div class="pv-row"><div style="display:flex;align-items:center;gap:10px"><span style="font-size:20px">🌙</span><span class="pv-label">Dark Mode</span></div><div class="pv-switch pv-switch-on"><div class="pv-thumb"></div></div></div><div class="pv-row"><div style="display:flex;align-items:center;gap:10px"><span style="font-size:20px">🔔</span><span class="pv-label">Notifications</span></div><div class="pv-switch pv-switch-off"><div class="pv-thumb"></div></div></div><div class="pv-row"><div style="display:flex;align-items:center;gap:10px"><span style="font-size:20px">📍</span><span class="pv-label">Location</span></div><div class="pv-switch pv-switch-on"><div class="pv-thumb"></div></div></div></div></div>`,

tabbar: `<div style="width:100%;max-width:300px;background:rgba(242,242,247,0.97);border-radius:12px;overflow:hidden;border:1px solid #E5E5EA"><div style="height:60px;display:flex;align-items:center;justify-content:center;font-size:13px;color:#8E8E93;background:white">Content Area</div><div class="pv-tabbar"><div class="pv-tab-item pv-active"><div class="pv-tab-icon">🏠</div><span>Home</span></div><div class="pv-tab-item"><div class="pv-tab-icon">🔍</div><span>Search</span></div><div class="pv-tab-item"><div class="pv-tab-icon">💬</div><span>Messages</span></div><div class="pv-tab-item"><div class="pv-tab-icon">👤</div><span>Profile</span></div></div></div>`,

table: `<div style="width:100%;max-width:300px;background:white;border-radius:12px;overflow:hidden;font-size:13px"><div style="display:grid;grid-template-columns:1fr 1fr 1fr;background:#F2F2F7;padding:8px 12px;font-weight:600;color:#8E8E93;border-bottom:0.5px solid #E5E5EA"><span>Name</span><span>Dept</span><span>Role</span></div><div style="display:grid;grid-template-columns:1fr 1fr 1fr;padding:8px 12px;border-bottom:0.5px solid #E5E5EA;background:rgba(0,122,255,0.05)"><span>Alice K.</span><span>Design</span><span>Lead</span></div><div style="display:grid;grid-template-columns:1fr 1fr 1fr;padding:8px 12px;border-bottom:0.5px solid #E5E5EA"><span>Bob L.</span><span>Eng</span><span>Senior</span></div><div style="display:grid;grid-template-columns:1fr 1fr 1fr;padding:8px 12px;background:rgba(0,122,255,0.05)"><span>Carol M.</span><span>PM</span><span>Manager</span></div></div>`,

tabs: `<div style="width:100%;max-width:280px"><div class="pv-seg" style="margin-bottom:14px"><div class="pv-seg-item pv-active">Overview</div><div class="pv-seg-item">Details</div><div class="pv-seg-item">Reviews</div></div><div style="background:white;border-radius:10px;padding:14px 16px"><div style="font-size:15px;font-weight:600;margin-bottom:6px">Overview</div><div style="font-size:13px;color:#8E8E93;line-height:1.5">A comprehensive summary with key highlights and metrics about the selected item.</div></div></div>`,

textfield: `<div style="width:100%;max-width:260px;display:flex;flex-direction:column;gap:12px"><div><div style="font-size:12px;color:#8E8E93;margin-bottom:5px">Email</div><div style="background:white;border:1.5px solid #007AFF;border-radius:8px;padding:10px 12px;font-size:15px">john@example.com</div></div><div><div style="font-size:12px;color:#8E8E93;margin-bottom:5px">Bio</div><div style="background:white;border:1px solid #E5E5EA;border-radius:8px;padding:10px 12px;font-size:15px;color:#C7C7CC;height:60px">Tell us about yourself...</div></div></div>`,

timeline: `<div style="width:100%;max-width:260px"><div style="display:flex;gap:12px;align-items:flex-start;padding-bottom:14px"><div style="display:flex;flex-direction:column;align-items:center"><div style="width:10px;height:10px;border-radius:5px;background:#007AFF;flex-shrink:0"></div><div style="width:2px;flex:1;background:#E5E5EA;min-height:28px;margin-top:3px"></div></div><div><div style="font-size:14px;font-weight:500">App Submitted</div><div style="font-size:12px;color:#8E8E93">Mar 6, 2026</div></div></div><div style="display:flex;gap:12px;align-items:flex-start;padding-bottom:14px"><div style="display:flex;flex-direction:column;align-items:center"><div style="width:10px;height:10px;border-radius:5px;background:#34C759;flex-shrink:0"></div><div style="width:2px;flex:1;background:#E5E5EA;min-height:28px;margin-top:3px"></div></div><div><div style="font-size:14px;font-weight:500">Review Approved</div><div style="font-size:12px;color:#8E8E93">Mar 4, 2026</div></div></div><div style="display:flex;gap:12px;align-items:flex-start"><div style="width:10px;height:10px;border-radius:5px;background:#8E8E93;flex-shrink:0;margin-top:2px"></div><div><div style="font-size:14px;font-weight:500;color:#8E8E93">In Review</div><div style="font-size:12px;color:#8E8E93">Mar 1, 2026</div></div></div></div>`,

tipview: `<div style="display:flex;flex-direction:column;align-items:center;gap:12px;width:100%;max-width:280px"><button style="display:flex;align-items:center;gap:8px;background:white;border:1px solid #E5E5EA;border-radius:10px;padding:10px 16px;font-size:15px;cursor:default;font-family:inherit"><span style="font-size:20px">❤️</span>Like</button><div style="background:white;border:1px solid #E5E5EA;border-radius:12px;padding:14px 16px;width:100%;box-shadow:0 4px 12px rgba(0,0,0,0.08)"><div style="display:flex;gap:12px;align-items:flex-start"><div style="width:40px;height:40px;border-radius:10px;background:rgba(255,45,85,0.1);display:flex;align-items:center;justify-content:center;font-size:20px;flex-shrink:0">❤️</div><div><div style="font-size:14px;font-weight:600;margin-bottom:3px">Save Favorites</div><div style="font-size:12px;color:#8E8E93;line-height:1.4">Tap the heart to save items to your favorites list.</div></div></div></div></div>`,

toolbar: `<div style="width:100%;max-width:300px;background:white;border-radius:12px;overflow:hidden;border:1px solid #E5E5EA"><div style="padding:10px 16px;display:flex;justify-content:space-between;align-items:center;border-bottom:0.5px solid #E5E5EA"><div style="font-size:15px;font-weight:600">Document</div><div style="display:flex;gap:6px"><button style="width:34px;height:34px;border:none;background:rgba(0,122,255,0.1);border-radius:8px;font-size:15px;cursor:default">↑</button><button style="width:34px;height:34px;border:none;background:rgba(0,122,255,0.1);border-radius:8px;font-size:15px;cursor:default">✏️</button><button style="width:34px;height:34px;border:none;background:rgba(255,59,48,0.1);border-radius:8px;font-size:15px;cursor:default">🗑️</button></div></div><div style="padding:12px 16px;font-size:13px;color:#8E8E93">Content area</div></div>`,

treeview: `<div class="pv-wrap"><div class="pv-card"><div class="pv-row"><span style="font-size:12px;color:#8E8E93;margin-right:6px;width:12px">▼</span><span style="font-size:16px;margin-right:8px">📁</span><span class="pv-label">Documents</span></div><div class="pv-row" style="padding-left:28px"><span style="font-size:12px;color:#8E8E93;margin-right:6px;width:12px">▶</span><span style="font-size:16px;margin-right:8px">📁</span><span class="pv-label">Work</span></div><div class="pv-row" style="padding-left:52px"><span style="font-size:16px;margin-right:8px">📄</span><span class="pv-label">Report.pdf</span></div><div class="pv-row" style="padding-left:52px"><span style="font-size:16px;margin-right:8px">📊</span><span class="pv-label">Budget.xlsx</span></div><div class="pv-row" style="padding-left:28px"><span style="font-size:12px;color:#8E8E93;margin-right:6px;width:12px">▶</span><span style="font-size:16px;margin-right:8px">📁</span><span class="pv-label">Personal</span></div></div></div>`,

video: `<div style="width:100%;max-width:300px;background:#000;border-radius:12px;overflow:hidden"><div style="height:120px;background:linear-gradient(135deg,#1a1a2e,#16213e,#0f3460);display:flex;align-items:center;justify-content:center"><div style="width:52px;height:52px;border-radius:26px;background:rgba(255,255,255,0.9);display:flex;align-items:center;justify-content:center;font-size:22px;padding-left:4px">▶</div></div><div style="background:#1C1C1E;padding:10px 14px"><div style="height:3px;background:#444;border-radius:2px;margin-bottom:10px;position:relative"><div style="position:absolute;left:0;top:0;width:35%;height:100%;background:#FF453A;border-radius:2px"></div><div style="position:absolute;left:35%;top:50%;transform:translate(-50%,-50%);width:12px;height:12px;background:white;border-radius:6px"></div></div><div style="display:flex;justify-content:space-between;align-items:center"><div style="display:flex;gap:14px"><span style="font-size:16px;color:white;cursor:default">⏮</span><span style="font-size:16px;color:white;cursor:default">▶</span><span style="font-size:16px;color:white;cursor:default">⏭</span></div><span style="font-size:12px;color:#8E8E93">0:42 / 2:03</span><div style="display:flex;gap:12px"><span style="font-size:15px;color:white">🔊</span></div></div></div></div>`,

widget: `<div style="display:flex;gap:10px;align-items:flex-start;justify-content:center"><div style="width:150px;height:150px;background:linear-gradient(135deg,#007AFF,#5856D6);border-radius:22px;padding:14px;display:flex;flex-direction:column;justify-content:space-between;flex-shrink:0"><div style="display:flex;justify-content:space-between;align-items:center"><div style="font-size:22px">⌘</div><div style="font-size:10px;color:rgba(255,255,255,0.7);text-align:right">Gallery</div></div><div><div style="font-size:38px;font-weight:700;color:white;line-height:1">60</div><div style="font-size:12px;color:rgba(255,255,255,0.8)">Components</div></div></div><div style="display:flex;flex-direction:column;gap:8px"><div style="width:70px;height:70px;background:linear-gradient(135deg,#34C759,#30D158);border-radius:16px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px"><div style="font-size:24px">📱</div><div style="font-size:9px;color:rgba(255,255,255,0.9)">iOS</div></div><div style="width:70px;height:70px;background:linear-gradient(135deg,#FF9500,#FF6B00);border-radius:16px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px"><div style="font-size:24px">💻</div><div style="font-size:9px;color:rgba(255,255,255,0.9)">macOS</div></div></div></div>`,

colorpicker: `<div style="width:100%;max-width:280px"><div style="background:white;border-radius:10px;padding:10px 14px;display:flex;justify-content:space-between;align-items:center;margin-bottom:10px"><span style="font-size:15px">Theme Color</span><div style="display:flex;gap:8px;align-items:center"><div style="width:28px;height:28px;border-radius:7px;background:#007AFF;border:1px solid rgba(0,0,0,0.1)"></div><span style="font-size:13px;color:#8E8E93">#007AFF</span></div></div><div style="background:white;border-radius:12px;padding:14px"><div style="width:100%;height:90px;border-radius:8px;background:linear-gradient(to bottom,transparent,#000),linear-gradient(to right,#fff,#007AFF);margin-bottom:10px;position:relative;overflow:hidden"><div style="position:absolute;bottom:28px;right:24px;width:14px;height:14px;border-radius:7px;border:2.5px solid white;box-shadow:0 0 0 1px rgba(0,0,0,0.2)"></div></div><div style="height:12px;border-radius:6px;background:linear-gradient(to right,#F00,#FF0,#0F0,#0FF,#00F,#F0F,#F00);position:relative"><div style="position:absolute;top:-2px;left:28%;width:16px;height:16px;border-radius:8px;border:2.5px solid white;box-shadow:0 0 0 1px rgba(0,0,0,0.2)"></div></div></div></div>`,

sharesheet: `<div style="width:100%;max-width:300px;background:white;border-radius:16px;overflow:hidden;box-shadow:0 -4px 20px rgba(0,0,0,0.1)"><div style="padding:14px 16px;border-bottom:0.5px solid #E5E5EA;text-align:center;font-size:13px;color:#8E8E93">Share "My App"</div><div style="padding:12px;display:flex;gap:14px;justify-content:center"><div style="display:flex;flex-direction:column;align-items:center;gap:5px"><div style="width:52px;height:52px;background:rgba(0,122,255,0.1);border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:24px">💬</div><span style="font-size:11px">Message</span></div><div style="display:flex;flex-direction:column;align-items:center;gap:5px"><div style="width:52px;height:52px;background:rgba(52,199,89,0.1);border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:24px">📧</div><span style="font-size:11px">Mail</span></div><div style="display:flex;flex-direction:column;align-items:center;gap:5px"><div style="width:52px;height:52px;background:rgba(255,149,0,0.1);border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:24px">🔗</div><span style="font-size:11px">Copy Link</span></div><div style="display:flex;flex-direction:column;align-items:center;gap:5px"><div style="width:52px;height:52px;background:rgba(88,86,214,0.1);border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:24px">📋</div><span style="font-size:11px">Notes</span></div></div></div>`,

scrollview: `<div style="width:100%;max-width:280px;height:160px;overflow:hidden;position:relative;border-radius:12px"><div class="pv-card"><div class="pv-row"><span class="pv-label">First Item</span><span class="pv-chev"></span></div><div class="pv-row"><span class="pv-label">Second Item</span><span class="pv-chev"></span></div><div class="pv-row"><span class="pv-label">Third Item</span><span class="pv-chev"></span></div><div class="pv-row"><span class="pv-label">Fourth Item</span><span class="pv-chev"></span></div><div class="pv-row"><span class="pv-label">Fifth Item</span><span class="pv-chev"></span></div><div class="pv-row"><span class="pv-label">Sixth Item</span><span class="pv-chev"></span></div></div><div style="position:absolute;bottom:0;left:0;right:0;height:48px;background:linear-gradient(to bottom,transparent,rgba(242,242,247,0.95));pointer-events:none"></div><div style="position:absolute;top:10%;right:3px;width:4px;height:40%;background:rgba(0,0,0,0.18);border-radius:2px"></div></div>`,

statusbar: `<div style="width:100%;max-width:300px;background:white;border-radius:12px;overflow:hidden;border:1px solid #E5E5EA"><div style="background:#000;padding:8px 20px;display:flex;justify-content:space-between;align-items:center"><span style="font-size:15px;font-weight:600;color:white">9:41</span><div style="display:flex;gap:5px;align-items:center"><div style="display:flex;gap:1px;align-items:flex-end"><div style="width:3px;height:5px;background:white;border-radius:1px"></div><div style="width:3px;height:8px;background:white;border-radius:1px"></div><div style="width:3px;height:11px;background:white;border-radius:1px"></div><div style="width:3px;height:14px;background:white;border-radius:1px"></div></div><span style="font-size:12px;color:white">WiFi</span><span style="font-size:14px">🔋</span></div></div><div style="padding:16px;font-size:13px;color:#8E8E93;text-align:center">Content below status bar</div></div>`,

};
